# Docker compose example;
# Service for managing multiple containers;
# Micro service architecture;
# Containers communicate between each other via service name rather IP address.

FROM python:3.11-buster
LABEL developer="rohitakurdekar"
LABEL "maintainer"="diot-jan-2023"
WORKDIR /code/python_app
COPY user_driven_input.py /code/python_app/
