version: '3.3'
services:
# -------- MQTTbroker --------------------
  mqttbroker:
    build: ./MQTT_broker
    # image: ubuntu:mqtt_brokerV1
    hostname: mosquitto_broker_c
    container_name: mqc_broker
    networks:
      - default 
    expose:
      - 1883
    ports:
      - 6800:1883

# -------- MQTTpublisher --------------------
  mqttpub:
    build: ./MQTT_PUB
    hostname: mosquitto_pub_c
    container_name: mqc_pub
    networks:
      - default 
    command:  python3 publisher.py
    depends_on:
      - mqttbroker

# -------- MQTTsubscriber --------------------
  mqttsub:
    build: ./MQTT_SUB
    hostname: mosquitto_sub_c
    container_name: mqc_sub
    networks:
      - default 
    command:  python3 subscriber.py
    depends_on:
      - mqttbroker

# -------- MQTT_REST_POST --------------------
  mqttrest:
    build: ./REST_thingspeak
    hostname: mosquitto_rest_c
    container_name: mqc_rest
    networks:
      - default 
    command:  python3 REST_API.py
    depends_on:
      - mqttbroker

